sudo: required
dist: trusty

language: cpp

compiler: gcc

env:
    global:
        - secure: "yh8QSkvdO3pg4lhQSlkBDlj09X7YARUqelGydKX5+xiJOsKXgpZP4GvBdhtBuqkXLtSl6+9mFL2Xstt4IUu2Frhyi3bZNTZIIIW8oy/vlHhui57dwf/GrISYJaofeUbWbQvaITQwFfdmJZe1KE5ar7/fQNuYXxOxec5+PuV9PlTPT3Q8mBY/T+egix6Riv+uoHfdyDM0MWIOnE85Am3G56W2Vdgkpau5BMBC1wLhXkUNoaKr6Hfi5SbGXEQj41/5G7+uvHM4uhIYx/ZzhA0kdyZKQL/kdPHShhqsNRYusQ0oSBgekAgeJ95gFQl05NXxFCZUgJIZp78uMmEDkkK+yr3I9yg0qkuKBRCDuroFccUHqtPZQ9H4jTJ6M/nEfJCbYy769i65oJbHZl5IrDmoIBu2NvokYJ+TjrDSPnFMlseGyWMiRze9udv3stzaedTwEM4vaCpTnNHFInMhUvae3FE6La1EY0MoUWm0gX2vrwosDm3dTrRakrRBYFJ7X3J7h1aswGvOP44WGGnSsMfmhTTem9c9DnZZHjvacemcUboEHXchiTwpRD3CEMQX2Ea+sLl5GlmuGv5dggcG20zjS8cgDFIpYOqBP7AJwX05w6ZMRn4AltTbKjhSuN2oXTAEdydhzY0pNB5ZgI5drUV2Kn0TbkK7qti5eZP5JYirBLE="
        - QT_VERSION=58 QT_SOURCE=58 GCC_VERSION=6

addons:
    coverity_scan:
        project:
            name: "rakhimov/verdigris"
            # description: "Build submitted via Travis CI"
        notification_email: ol.rakhimov@gmail.com
        build_command_prepend: qmake
        build_command: make -j 2
        branch_pattern: "coverity_scan"
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.8
            - llvm-toolchain-trusty-3.9
            - llvm-toolchain-trusty-4.0
            - llvm-toolchain-trusty-5.0

before_install:
    - if [[ ${QT_VERSION} == "510" ]]; then
        sudo add-apt-repository -y ppa:forkotov02/opt-qt-${QT_SOURCE}-trusty;
      else
        sudo add-apt-repository -y ppa:beineri/opt-qt${QT_SOURCE}-trusty;
      fi
    - sudo apt-get update

install:
    - sudo apt-get install -y -qq qt${QT_VERSION}base
    - if [[ $GCC_VERSION ]]; then
        sudo apt-get install -y -qq g++-${GCC_VERSION};
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-${GCC_VERSION} 90;
        g++ --version;
      elif [[ $CLANG_VERSION ]]; then
        sudo apt-get install -y -qq libstdc++-5-dev clang-${CLANG_VERSION};
        sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-${CLANG_VERSION} 90;
        clang++ --version;
        export QMAKESPEC=linux-clang;
      fi

before_script:
    - source /opt/qt$QT_VERSION/bin/qt${QT_VERSION}-env.sh

script: true
